<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CP_SmokeTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>dcd18c20-13bf-46ed-9616-d7b2698e3608</testSuiteGuid>
   <testCaseLink>
      <guid>09af5ab5-2abd-4ad7-9c98-c1c311e5defd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ClaimsPortalLogin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>46276381-63dc-414f-a4dc-2ae8a5d54fdb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginCredential</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>46276381-63dc-414f-a4dc-2ae8a5d54fdb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserName</value>
         <variableId>3c0ac037-99d1-4006-b45f-39bac9223df3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>46276381-63dc-414f-a4dc-2ae8a5d54fdb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>7583c928-3c03-4e82-8805-fc33c9443dcc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
