<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout_top-nav-logout</name>
   <tag></tag>
   <elementGuidId>d7c0dee7-95bc-42a6-92d0-d762243549dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a.top-nav-logout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-bar']/div[3]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f454d09d-5468-42a2-8c66-59d3b11f0bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:document.getElementById('logoutForm').submit()</value>
      <webElementGuid>b1a8edb4-5012-4bb0-b4f1-0262886350f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-nav-logout</value>
      <webElementGuid>f3162578-4e1f-431d-b981-51ba30579925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>f65efe88-60ea-47d1-a9ed-af03bd0e2369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-bar&quot;)/div[@class=&quot;top-nav-right-menu&quot;]/div[@class=&quot;navbar-collapses&quot;]/ul[@class=&quot;nav navbar-nav navbar-right top-menu&quot;]/li[2]/a[@class=&quot;top-nav-logout&quot;]</value>
      <webElementGuid>2176ded9-1b24-4b7c-9f74-c802f953a4e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-bar']/div[3]/div/ul/li[2]/a</value>
      <webElementGuid>b2cf08da-a687-4ad0-b728-4bf645ecb011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, &quot;javascript:document.getElementById('logoutForm').submit()&quot;)])[2]</value>
      <webElementGuid>5445e9f0-743f-45a5-af7f-e2324133bfdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>b3fe5a37-b903-475a-a03b-5a5c1736eae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:document.getElementById(&quot; , &quot;'&quot; , &quot;logoutForm&quot; , &quot;'&quot; , &quot;).submit()&quot;) and @title = 'Logout']</value>
      <webElementGuid>c5a90ca8-e988-443f-88d0-9f28ea9c70cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
