<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status Start Date_StatusDateStart</name>
   <tag></tag>
   <elementGuidId>f5548ce9-39d0-42ff-afee-66e29c393d9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='StatusDateStart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#StatusDateStart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Status Start Date&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f305a57-39b3-476e-91a5-36300ea5643e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hasDatepicker</value>
      <webElementGuid>900b88c3-a8d2-4ca6-a40c-0054494f5f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>13501999-a3f4-48b7-9a90-fe28ca709375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field StatusDateStart must be a date.</value>
      <webElementGuid>bcd5d06f-aed7-4590-8fcf-b389b0f08f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The StatusDateStart field is required.</value>
      <webElementGuid>ad78bb84-6f84-453e-8d0b-5f79646bc1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StatusDateStart</value>
      <webElementGuid>d1deafdc-6bf7-4d3b-b042-266a54db5cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StatusDateStart</value>
      <webElementGuid>c32f28e6-6fd5-4bd5-b980-9038ad3f2446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Status Start Date</value>
      <webElementGuid>7a136352-680c-4c0b-9c62-99c40e262e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f915d0c-0dfa-440c-ba62-b62e0f1e43e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1/01/0001</value>
      <webElementGuid>72565099-1d4f-4afe-8f9c-4b5be7efca4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StatusDateStart&quot;)</value>
      <webElementGuid>24ce2a4a-f41d-4010-831b-ba4d3deb9f89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='StatusDateStart']</value>
      <webElementGuid>dac10c90-edc3-4840-adc2-09f62d33cc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SearchResultsForm']/div[3]/div[2]/div/input</value>
      <webElementGuid>0fe30ec1-197d-4d90-a9c7-3c075702e561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>c1b08964-70f5-4338-8eb9-95904dfa39e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'StatusDateStart' and @name = 'StatusDateStart' and @placeholder = 'Status Start Date' and @type = 'text']</value>
      <webElementGuid>4c299bf8-9333-4d5a-b3d0-f9287612d0c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
