<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Certificate Effective Date_CertEffectiveDate</name>
   <tag></tag>
   <elementGuidId>9bfb89d5-9d6a-45ce-a2c0-fcc0123d483b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CertEffectiveDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CertEffectiveDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Select Certificate Effective Date&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98e704f1-10af-4fc8-9870-b1eb0b781e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5ed17403-3985-490d-a60c-715a64797525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hasDatepicker</value>
      <webElementGuid>5bd4a51f-47a3-4ed8-8165-d636de818458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e1da7ff8-5364-489c-85d6-aa7edd06b4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Certificate Effective Date must be a date.</value>
      <webElementGuid>052525c0-8caa-49fa-bed1-23afb9e96f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Please enter Certificate Effective Date.</value>
      <webElementGuid>340c46fd-dbe8-4df4-a2fd-d4011045e099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CertEffectiveDate</value>
      <webElementGuid>8c55055d-2993-4fef-8d4b-9bd4bba55d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>d5eb56a8-5f6d-4ad9-8463-ee0aec9f81ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CertEffectiveDate</value>
      <webElementGuid>fb194bb5-3ae2-4ff0-8f6d-8e8dd734ca25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Certificate Effective Date</value>
      <webElementGuid>ede63d59-5e58-40c0-b1b9-be618d8c1627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d14253e-a294-4b93-bad6-6275cae6ad34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1/01/0001</value>
      <webElementGuid>c8403e6f-f8fb-43e5-9bd1-5fef5f91f8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CertEffectiveDate&quot;)</value>
      <webElementGuid>3682e567-a3eb-415a-bc7e-6c8db7a52552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CertEffectiveDate']</value>
      <webElementGuid>ad463d74-8f69-48e8-bd69-81374bf6f5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='__AjaxAntiForgeryForm']/div[2]/div[3]/div/input</value>
      <webElementGuid>c8fcc061-54c0-4cd9-a107-bc300e328336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>21df9d0e-49ea-4cfa-bc3a-dd10510005ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CertEffectiveDate' and @name = 'CertEffectiveDate' and @placeholder = 'Select Certificate Effective Date' and @type = 'text']</value>
      <webElementGuid>1ce1bc5f-a009-4391-b2cf-079a18e9c2fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
