<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_In Force_btnreq</name>
   <tag></tag>
   <elementGuidId>6272fc5e-f972-440f-a9a2-e00d4d0493f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnreq']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnreq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;SARA BAREFIELD 0045339835 DISABILITY 1966-12-24 2022-02-15 2024-02-15 In Force Request Claim&quot;i] >> #btnreq</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab76c19f-e50b-49c0-affd-9d43e5771e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnreq</value>
      <webElementGuid>b753cd2d-3e44-4d77-9a56-942653b30e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-datatables</value>
      <webElementGuid>5bee4f1a-ede0-4be4-92b2-cb3aeeafc687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7868b0b1-bdb3-44fe-bb41-aa02f05ca3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Request Claim</value>
      <webElementGuid>3766d5ea-e64b-4956-a7d1-0521e67ea6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>agentid</name>
      <type>Main</type>
      <value>FFGA004</value>
      <webElementGuid>19927d96-4d92-4b6d-889d-882d468f98fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>suffix</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d61eabbc-ed71-411d-8225-0b297f6594c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>coverage</name>
      <type>Main</type>
      <value>201</value>
      <webElementGuid>19a007ad-6685-4e5e-8a9f-210fa1a9ae5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>instype</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9046751a-2da4-482c-b318-d2b420991973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcode</name>
      <type>Main</type>
      <value>GAFARMER</value>
      <webElementGuid>c67a4b27-4e88-4040-87ad-df12ac157ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>insurednbr</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9821c838-f45d-4f82-a714-75fe125bdd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>agentstate</name>
      <type>Main</type>
      <value>GA</value>
      <webElementGuid>01bd1d1a-bb25-44e8-b15b-6270027b48f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>company</name>
      <type>Main</type>
      <value>LS</value>
      <webElementGuid>dd97fb5b-3a80-4a5f-a420-6357f7253801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>productline</name>
      <type>Main</type>
      <value>DISABILITY</value>
      <webElementGuid>7317c555-b72f-4d76-88b7-ad9c8d17d823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResults&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[11]/input[@id=&quot;btnreq&quot;]</value>
      <webElementGuid>8b7458f3-e5b4-4d45-a026-bf6d3f847776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnreq']</value>
      <webElementGuid>7b442b1e-29d9-49ad-81ed-20a74446c3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='searchResults']/tbody/tr/td[11]/input</value>
      <webElementGuid>b3ec256a-71a7-4b12-9f71-4b9bf423765a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/input</value>
      <webElementGuid>6ffcd8dd-b958-4344-9ca3-993c472a3960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'btnreq' and @type = 'button']</value>
      <webElementGuid>45e42663-1db0-42ba-b683-a0553d054e7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
