<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Back to Upload Documents</name>
   <tag></tag>
   <elementGuidId>34983d4e-a8b3-4469-ac35-e93e199f5b54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lnkbackReview']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lnkbackReview</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Back to Upload Documents&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc6172c4-d9e2-4f26-86bd-0043b85be111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lnkbackReview</value>
      <webElementGuid>798c9e65-90d7-43dd-ba90-bcf6f70b675e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-panel-previous</value>
      <webElementGuid>17acfbb4-5205-42d9-9576-fc07ed82079a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to Upload Documents</value>
      <webElementGuid>d4bbd708-fd8c-47e7-a9b1-5d59bb30d5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lnkbackReview&quot;)</value>
      <webElementGuid>881e9970-8eb1-477f-9f2b-f8a8bfef96bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lnkbackReview']</value>
      <webElementGuid>661802da-6ec9-43de-8dc5-3bcbc1d4036e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review']/div/div[5]/div/a</value>
      <webElementGuid>da9dcdb5-6644-48fc-8a04-08c75337a14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Back to Upload Documents')]</value>
      <webElementGuid>9d635768-073b-45ef-9467-427c45e983ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation'])[1]/preceding::a[1]</value>
      <webElementGuid>9e7e7eac-da52-4235-9872-9a44141087fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SARA  BAREFIELD'])[1]/preceding::a[1]</value>
      <webElementGuid>b8ac1e1c-35a3-40f4-98af-a39ff5f44594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back to Upload Documents']/parent::*</value>
      <webElementGuid>79d4d2fa-8d0d-4eac-9914-3c6edf50525f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>440202fa-f922-414f-93b7-55e05088a482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lnkbackReview' and (text() = 'Back to Upload Documents' or . = 'Back to Upload Documents')]</value>
      <webElementGuid>b8c170c6-6754-4785-b632-777df882644c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
