<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go to Review</name>
   <tag></tag>
   <elementGuidId>61ff6e3b-91e0-4bdc-8a76-5203d6808fee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lnknextUploadDocs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lnknextUploadDocs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Go to Review&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>341b85ec-e1bf-4179-8472-5f14a661bf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lnknextUploadDocs</value>
      <webElementGuid>6ded77c0-b6bf-4551-9189-d07b5b286ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-panel-next</value>
      <webElementGuid>b04fd5fc-fb63-4d4b-a717-a3e21162174d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go to Review</value>
      <webElementGuid>f9ceb972-229d-45c6-b079-494d74253ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lnknextUploadDocs&quot;)</value>
      <webElementGuid>30aad62a-fd3e-43db-a539-06904ec957d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lnknextUploadDocs']</value>
      <webElementGuid>8d3d2876-9d84-4456-845f-876d9924d71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uploadDocuments']/div/div[4]/div[2]/a</value>
      <webElementGuid>ef8674ec-2a35-4da8-8d19-d1421fdae999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go to Review')]</value>
      <webElementGuid>d72e2680-0a90-4360-80ca-5134874648d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Claim Forms'])[1]/following::a[1]</value>
      <webElementGuid>87a47eff-3750-49a6-a62c-d0f17a27a4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select/Drop'])[1]/following::a[2]</value>
      <webElementGuid>c4373d9e-f4b8-4e37-be8f-c88fd602884f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Documents'])[1]/preceding::a[1]</value>
      <webElementGuid>c1dcec97-6885-4c4a-b229-1d874b9ee6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required Documents'])[1]/preceding::a[1]</value>
      <webElementGuid>1c487ae4-416b-4aa2-b4d0-d209f54b93ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go to Review']/parent::*</value>
      <webElementGuid>e5166d21-70d7-456b-af57-c6531d4c0bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[4]/div[2]/a</value>
      <webElementGuid>dd0e4895-0574-4258-82c0-7884ef0f13fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lnknextUploadDocs' and (text() = 'Go to Review' or . = 'Go to Review')]</value>
      <webElementGuid>a95d3bba-1e36-4287-81b2-3f3ea7ae9106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
