<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go to Upload Documents</name>
   <tag></tag>
   <elementGuidId>1916911c-02ff-4813-b13a-003a7f743c2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lnknextClaimForm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lnknextClaimForm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Go to Upload Documents&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f1b01bcb-ab1d-49fd-9e63-d4505379214d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lnknextClaimForm</value>
      <webElementGuid>6fedf7a2-d60b-4df9-8d28-6575e20e2bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-panel-next</value>
      <webElementGuid>314b8ac8-16ac-4c91-93b5-0352ff82e12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go to Upload Documents</value>
      <webElementGuid>4ff3d5e3-7292-4e04-80bd-1f7e79586eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lnknextClaimForm&quot;)</value>
      <webElementGuid>92e5f278-34a9-4a20-8511-3cb99ca93456</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lnknextClaimForm']</value>
      <webElementGuid>3a9294e5-dec3-4b1f-8d72-5b0fb25a1420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='claimForms']/div/div[4]/div[2]/a</value>
      <webElementGuid>c979ea2e-4803-4da7-be42-e6eb8986cb7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go to Upload Documents')]</value>
      <webElementGuid>085963a4-8658-4ca2-b42e-1f5604165581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Information'])[2]/following::a[1]</value>
      <webElementGuid>b2627fd3-465b-47bc-8f6a-2984d09478ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disability / Dismemberment / Loss Of Sight Form'])[1]/following::a[2]</value>
      <webElementGuid>df99e8f7-e533-42c5-bbe8-58dc7926d635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Documents'])[2]/preceding::a[1]</value>
      <webElementGuid>53c07f5d-9f61-47be-8e0e-124e76519261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Name'])[1]/preceding::a[1]</value>
      <webElementGuid>e0a74714-8558-4386-97b4-073b3566260c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go to Upload Documents']/parent::*</value>
      <webElementGuid>b168d02a-cc90-4753-91fd-fe6eae4a4075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/a</value>
      <webElementGuid>a3721c65-7611-4554-bb4b-9bab1866a246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lnknextClaimForm' and (text() = 'Go to Upload Documents' or . = 'Go to Upload Documents')]</value>
      <webElementGuid>01989aa9-6fad-49a2-9f09-efe5829d17ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
