<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Claimant Address Line 2_Address2</name>
   <tag></tag>
   <elementGuidId>ae9e3d90-6b52-4eb2-9039-503e3f43af7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Address2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Address2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;APARTMENT/BUILDING/FLOOR/SUITE/UNIT&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2f60446-a2ce-45f5-8970-d59f034dd4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>cfd040f3-b7cb-4009-a64d-ee62dae4a852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>078987d5-e798-43ee-9814-7a0053285553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address2</value>
      <webElementGuid>3ee31812-2114-40fd-8954-ff7399fbcc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address2</value>
      <webElementGuid>402816c7-c466-45bc-bdc0-b3b188d61a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>APARTMENT/BUILDING/FLOOR/SUITE/UNIT</value>
      <webElementGuid>47c5073d-59a2-4ba1-9584-fc6f4adfe906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ac3b60e-7394-4f1c-97f4-049287be28fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address2&quot;)</value>
      <webElementGuid>e3ab8208-8bb6-4e87-a639-9282583ff2f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address2']</value>
      <webElementGuid>6d75a932-45be-4674-aa34-d84462e449c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information']/div/div[3]/div[4]/div[3]/div/input</value>
      <webElementGuid>7282ead7-450d-46e1-a8c7-8f12a5f72020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/input</value>
      <webElementGuid>a8fa5d7b-d763-4127-bc46-bea19c3b1a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Address2' and @name = 'Address2' and @placeholder = 'APARTMENT/BUILDING/FLOOR/SUITE/UNIT' and @type = 'text']</value>
      <webElementGuid>cefea848-c9d3-42b2-8965-557948e32c39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
